// accounts
export const ACCOUNT_DOES_NOT_EXIST_ERROR = 'ACCOUNT_DOES_NOT_EXIST_ERROR';
// authentication
export const AUTHENTICATION_METHOD_NOT_SUPPORTED_ERROR = 'AUTHENTICATION_METHOD_NOT_SUPPORTED_ERROR';
export const FAILED_TO_AUTHENTICATE_PASSKEY_ERROR = 'FAILED_TO_AUTHENTICATE_PASSKEY_ERROR';
export const FAILED_TO_REGISTER_PASSKEY_ERROR = 'FAILED_TO_REGISTER_PASSKEY_ERROR';
export const INVALID_PASSWORD_ERROR = 'INVALID_PASSWORD_ERROR';
export const NOT_AUTHENTICATED_ERROR = 'NOT_AUTHENTICATED_ERROR';
export const PASSKEY_NOT_SUPPORTED_ERROR = 'PASSKEY_NOT_SUPPORTED_ERROR';
export const USER_CANCELED_PASSKEY_REQUEST_ERROR = 'USER_CANCELED_PASSKEY_REQUEST_ERROR';
// avm
export const INVALID_AVM_ADDRESS_ERROR = 'INVALID_AVM_ADDRESS_ERROR';
// connectors
export const INVALID_CONNECTOR_ERROR = 'INVALID_CONNECTOR_ERROR';
// cryptography
export const DECRYPTION_ERROR = 'DECRYPTION_ERROR';
export const ENCRYPTION_ERROR = 'ENCRYPTION_ERROR';
export const INVALID_ACCOUNT_ERROR = 'INVALID_ACCOUNT_ERROR';
export const INVALID_PRIVATE_KEY_ERROR = 'INVALID_PRIVATE_KEY_ERROR';
// networks
export const FAILED_TO_FETCH_NETWORK_ERROR = 'FAILED_TO_FETCH_NETWORK_ERROR';
export const NETWORK_NOT_SUPPORTED_ERROR = 'NETWORK_NOT_SUPPORTED_ERROR';
// ui
export const FAILED_TO_RENDER_UI_ERROR = 'FAILED_TO_RENDER_UI_ERROR';
export const USER_CANCELED_UI_REQUEST_ERROR = 'USER_CANCELED_UI_REQUEST_ERROR';
