// accounts
export const ACCOUNT_DOES_NOT_EXIST_ERROR = 'ACCOUNT_DOES_NOT_EXIST_ERROR';
// authentication
export const FAILED_TO_AUTHENTICATE_PASSKEY_ERROR = 'FAILED_TO_AUTHENTICATE_PASSKEY_ERROR';
export const FAILED_TO_REGISTER_PASSKEY_ERROR = 'FAILED_TO_REGISTER_PASSKEY_ERROR';
export const PASSKEY_NOT_SUPPORTED_ERROR = 'PASSKEY_NOT_SUPPORTED_ERROR';
export const USER_CANCELED_PASSKEY_REQUEST_ERROR = 'USER_CANCELED_PASSKEY_REQUEST_ERROR';
// cryptography
export const DECRYPTION_ERROR = 'DECRYPTION_ERROR';
export const ENCRYPTION_ERROR = 'ENCRYPTION_ERROR';
export const INVALID_ACCOUNT_ERROR = 'INVALID_ACCOUNT_ERROR';
export const INVALID_PRIVATE_KEY_ERROR = 'INVALID_PRIVATE_KEY_ERROR';
// general
export const FAILED_TO_INITIALIZE_ERROR = 'FAILED_TO_INITIALIZE_ERROR';
