// authentication
export const FAILED_TO_AUTHENTICATE_PASSKEY_ERROR = 'FAILED_TO_AUTHENTICATE_PASSKEY_ERROR';
export const FAILED_TO_REGISTER_PASSKEY_ERROR = 'FAILED_TO_REGISTER_PASSKEY_ERROR';
export const PASSKEY_NOT_SUPPORTED_ERROR = 'PASSKEY_NOT_SUPPORTED_ERROR';
// cryptography
export const INVALID_ACCOUNT_ERROR = 'INVALID_ACCOUNT_ERROR';
export const INVALID_PRIVATE_KEY_ERROR = 'INVALID_PRIVATE_KEY_ERROR';
// vaults
export const VAULT_NOT_INITIALIZED_ERROR = 'VAULT_NOT_INITIALIZED_ERROR';
