packages:
  - packages/*

catalog:
  "@eslint/js": ^9.16.0
  "@kibisis/chains": ^2.5.0
  "@kibisis/encoding": ^1.0.1
  "@kibisis/utilities": ^1.0.0
  "@stablelib/random": ^2.0.1
  "@types/node": ^22.10.1
  "algosdk": ^3.3.1
  chalk: ^5.3.0
  concurrently: ^9.1.2
  eslint: ^9.16.0
  eslint-config-prettier: ^9.1.0
  globals: ^15.13.0
  prettier: ^3.2.5
  shx: ^0.3.4
  tsx: ^4.19.2
  typescript: ^5.7.2
  typescript-eslint: ^8.18.0
  vite: ^6.0.3
  vite-plugin-dts: ^4.3.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.5
