name: "\U0001F41B Bug"
description: "File a bug report"
title: "fix: "
labels: ["\U0001F41B bug"]
assignees:
  - kieranroneill

body:
  # welcome
  - attributes:
      value: |
        Thanks for taking the time to fill out this bug report, all issues are welcome and remember, you're awesome!
    type: markdown

  # contact details
  - attributes:
      description: "How can we get in touch with you if we need more info?"
      label: "Contact Details"
      placeholder: "e.g. email@example.com"
    id: contact
    type: input
    validations:
      required: false

  # version
  - attributes:
      description: "What version of the SDK are you running?"
      label: "Version"
      options:
        - 1.0.0
    id: version
    type: dropdown
    validations:
      required: true

  # browser
  - attributes:
      description: "What browser are you seeing the problem on?"
      label: "Browser"
      multiple: true
      options:
        - Brave
        - Chrome
        - Edge
        - Firefox
    id: browsers
    type: dropdown
    validations:
      required: false

  # summary
  - attributes:
      description: "Give a brief summary of the bug in one or two sentences."
      label: "Summary"
    id: summary
    type: textarea
    validations:
      required: true

  # steps to reproduce
  - attributes:
      label: "Steps To Reproduce"
      description: "Use a simple bulleted pointed list of the steps to reproduce."
    id: steps-to-reproduce
    type: textarea
    validations:
      required: true

  # expected results
  - attributes:
      description: "Give a brief description or bullet points of what you expect to happen."
      label: "Expected Results"
    id: expected-results
    type: textarea
    validations:
      required: true

  # actual results
  - attributes:
      description: "Give a brief description or bullet points of what actual happens."
      label: "Actual Results"
    id: actual-results
    type: textarea
    validations:
      required: true

  # logs
  - attributes:
      label: "Logs"
      description: "Please copy and paste any relevant browser console output. This will be automatically formatted into code, so no need for backticks."
      render: shell
    id: logs
    type: textarea
    validations:
      required: false
