name: "✨ Feature"
description: Suggest an idea or feature
title: "feat: "
labels: ["✨ feature"]
assignees:
  - kieraroneill

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request, all features are welcome and remember, you're awesome!

  - type: textarea
    attributes:
      label: Summary
      description: Tell us, what idea or feature you suggest to be added. This can be as simple as bulleted points or a detailed description.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Benefits
      description: Tell us, how this this will be beneficial.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Where can we find information about this?
      description: If you are proposing an integration or third-party plugins, please add relevant links and documentation.
    validations:
      required: false
