name: "Release"

on:
  push:
    branches:
      - beta
      - main

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true # ensure only one release workflow runs per branch (e.g., "release-beta" or "release-main")

permissions:
  contents: write # to be able to publish a github release
  issues: write # to be able to comment on released issues
  packages: write  # to be able to publish packages
  pull-requests: write # to be able to comment on released pull requests

jobs:
  documentation:
    name: "Release - documentation"
    uses: ./.github/workflows/workflow_call_version_release.yml
    with:
      package_dir: "documentation"

  core:
    name: "Release - @kibisis/katavault-core"
    needs: [documentation]
    uses: ./.github/workflows/workflow_call_publish_release.yml
    with:
      package_dir: "core"
      package_name: "@kibisis/katavault-core"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_PACKAGES_ACCESS_TOKEN }}

  # **MUST** come after [core] as it uses them as dependencies
  react:
    name: "Release - @kibisis/katavault-react"
    needs: [documentation, core]
    uses: ./.github/workflows/workflow_call_publish_release.yml
    with:
      package_dir: "react"
      package_name: "@kibisis/katavault-react"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_PACKAGES_ACCESS_TOKEN }}

  # **MUST** come after [core, react] as it uses them as dependencies
  sandbox:
    name: "Release - sandbox"
    needs: [documentation, core, react]
    uses: ./.github/workflows/workflow_call_version_release.yml
    with:
      package_dir: "sandbox"
