name: "Workflow call: version release"

on:
  workflow_call:
    inputs:
      package_dir:
        description: "The directory name of the package."
        required: true
        type: string

permissions:
  contents: write # to be able to publish a github release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # use the entire git history for semantic-release to analyze history
          submodules: recursive # ensure the git submodules are fetched
      - name: "⤵️ Pull Latest Changes"
        run: git pull origin ${{ github.ref_name }}
      - name: "🔧 Setup"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "🔖 Release"
        env:
          HUSKY: 0 # disable husky
          # appears on the release commits
          GIT_AUTHOR_NAME: kibi-bot
          GIT_AUTHOR_EMAIL: builders@kibis.is
          GIT_COMMITTER_NAME: kibi-bot
          GIT_COMMITTER_EMAIL: builders@kibis.is
          # used to push the release commit and create the tags
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec semantic-release -e semantic-release-monorepo
        working-directory: ./packages/${{ inputs.package_dir }}
